import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const prod = process.argv[2] === "production";
const OUT_DIR = "weixin-sync-test-vault/.obsidian/plugins/weixin-sync";

mkdirSync(OUT_DIR, { recursive: true });

// 将插件静态文件（manifest.json、styles.css、versions.json 等）一并拷贝进编译输出目录，
// 该目录即本地测试 vault 的 Obsidian 插件目录，编译后可直接在 Obsidian 中热重载。
for (const f of ["manifest.json", "styles.css", "versions.json"]) {
  if (existsSync(f)) {
    copyFileSync(f, `${OUT_DIR}/${f}`);
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  // 将图片作为 dataurl 内联打包，使小程序码等资源随 main.js 自包含分发，无需单独拷贝资源目录
  loader: { ".jpg": "dataurl", ".png": "dataurl", ".svg": "dataurl" },
  outfile: `${OUT_DIR}/main.js`,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
